[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.0.0",
    "python-telegram-bot[all]>=21.10",
    "schedule>=1.2.0",
    "sqlalchemy>=2.0.0",
]
